name: uso_xml
description: Taller de la asignatura de Desarrollo de Aplicaciones Móviles. Grupo 7.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/comida.xml
    - assets/data/Planta.xml
    - assets/data/receta.xml